spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: com.learn.springboot.dao.entity

# showsql
logging:
  level:
    com.learn.springboot.dao.mapper: DEBUG